# Generated by Django 5.0.6 on 2024-06-21 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstLevelUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('expiration_date', models.DateTimeField(verbose_name='到期时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '一级用户',
                'verbose_name_plural': '一级用户',
            },
        ),
        migrations.CreateModel(
            name='SecondLevelUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '二级用户',
                'verbose_name_plural': '二级用户',
            },
        ),
        migrations.CreateModel(
            name='PendingOrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(max_length=100, verbose_name='订单编号')),
                ('second_level_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hb.secondleveluser', verbose_name='二级用户')),
            ],
            options={
                'verbose_name': '待处理订单请求',
                'verbose_name_plural': '待处理订单请求',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='店铺名称')),
                ('approved', models.BooleanField(default=False, verbose_name='已审核')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hb.firstleveluser', verbose_name='所有者')),
            ],
            options={
                'verbose_name': '店铺',
                'verbose_name_plural': '店铺',
            },
        ),
        migrations.CreateModel(
            name='SecondLevelUserShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('second_level_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hb.secondleveluser', verbose_name='二级用户')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hb.shop', verbose_name='店铺')),
            ],
            options={
                'verbose_name': '二级用户店铺关联',
                'verbose_name_plural': '二级用户店铺关联',
            },
        ),
        migrations.AddField(
            model_name='secondleveluser',
            name='shops',
            field=models.ManyToManyField(through='hb.SecondLevelUserShop', to='hb.shop', verbose_name='店铺'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(max_length=100, verbose_name='订单编号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单金额')),
                ('status', models.CharField(choices=[('pending', '待发放'), ('distributed', '已发放'), ('expired', '已过期')], default='pending', max_length=20, verbose_name='状态')),
                ('tijiao', models.CharField(blank=True, max_length=100, null=True, verbose_name='提交人')),
                ('first_level_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hb.firstleveluser', verbose_name='一级用户')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hb.shop', verbose_name='店铺')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
    ]
