# Generated by Django 5.0.6 on 2024-06-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstleveluser',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='到期时间'),
        ),
    ]
