# Generated by Django 5.0.6 on 2024-06-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hb', '0002_alter_firstleveluser_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstleveluser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='账户余额'),
        ),
    ]
