# Generated by Django 5.0.6 on 2024-07-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hb', '0003_firstleveluser_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='订单编号'),
        ),
    ]
